// Dynamic Career Roadmap Data (Autogenerated from index.html)
export interface GuideData {
    goal?: string;
    "build this"?: string;
    "key concepts"?: string[];
    resources?: string[];
    checklist?: string[];
}

export interface RoadmapItem {
    id: string;
    title: string;
    desc: string;
    tags: string[];
    guide: GuideData;
}

export interface RoadmapPhase {
    id: string;
    badge: string;
    title: string;
    subtitle: string;
    items: RoadmapItem[];
}

export const roadmapData: RoadmapPhase[] = [
    {
        "id": "immediate",
        "badge": "⚡",
        "title": "Immediate Actions — Start Today",
        "subtitle": "Do not wait. These give you the biggest leverage right now.",
        "items": [
            {
                "id": "imm-1",
                "title": "Cursor IDE — Daily Driver",
                "desc": "Use Composer, Tab, and Agent mode for 80% of coding",
                "tags": [
                    "Critical"
                ],
                "guide": {
                    "goal": "Use Cursor as your primary IDE for all coding. AI should write 80% of boilerplate; you focus on architecture and review.",
                    "build this": "Migrate one existing MERN/Next.js project fully into Cursor. Use Tab for autocomplete, Cmd+K for inline edits, and Cmd+I (Composer) for multi-file refactors.",
                    "key concepts": [
                        "Composer mode (multi-file agentic editing)",
                        "Cursor Tab (predictive next-edit)",
                        "Context awareness (@files, @docs, @web)",
                        "AI review workflow: generate → read every line → test → ship"
                    ],
                    "resources": [
                        "Cursor.com — Download & docs",
                        "YouTube: \"Cursor AI Full Course\" by Fireship or similar",
                        "Practice: Rebuild a simple CRUD app using only AI prompts"
                    ]
                }
            },
            {
                "id": "imm-2",
                "title": "Claude Code / GitHub Copilot Agent",
                "desc": "Terminal-based AI for complex refactors and debugging",
                "tags": [
                    "Critical"
                ],
                "guide": {
                    "goal": "Use terminal-based AI agents for complex tasks: refactoring monoliths, debugging, test generation, and codebase-wide changes.",
                    "build this": "Take a messy legacy Node.js project. Use Claude Code to: (1) add TypeScript, (2) write tests for untested files, (3) refactor callback hell to async/await.",
                    "key concepts": [
                        "Agentic loops (AI plans → executes → verifies)",
                        "Slash commands (/test, /fix, /explain)",
                        "Context windows and file selection",
                        "Approval workflows (always review before accepting)"
                    ],
                    "resources": [
                        "Claude Code Docs",
                        "GitHub Copilot Agent Mode",
                        "Terminal workflow: Claude Code + tmux + git"
                    ]
                }
            },
            {
                "id": "imm-3",
                "title": "Vibe Coding Workflow",
                "desc": "Prompt → Review → Debug → Ship. Don't write boilerplate manually.",
                "tags": [
                    "Critical"
                ],
                "guide": {
                    "goal": "Develop a reliable workflow where AI generates 80% of code, but you maintain 100% understanding and quality control.",
                    "build this": "Build a full-stack app (e.g., a task manager) in 2 hours using only AI prompts. Time yourself. Then audit every line for security and logic errors.",
                    "key concepts": [
                        "Prompt engineering for code (be specific, give context)",
                        "Iterative refinement (don't accept first output)",
                        "Security review of AI-generated code (SQL injection, XSS)",
                        "Testing AI output before shipping"
                    ],
                    "resources": [
                        "Andrej Karpathy's \"Vibe Coding\" talk/concept",
                        "Practice: Project-Based Learning repo — pick one, build with AI"
                    ]
                }
            },
            {
                "id": "imm-4",
                "title": "RAG Chatbot with Vector DB",
                "desc": "Pinecone/Weaviate + OpenAI + Node.js/Python. Deploy it live.",
                "tags": [
                    "Portfolio"
                ],
                "guide": {
                    "goal": "Build a production-ready RAG (Retrieval-Augmented Generation) chatbot that can answer questions from your own documents with source citations.",
                    "build this": "Step-by-Step:1. Data Ingestion: Build PDF/TXT upload endpoint. Parse text using pdf-parse or LangChain document loaders.2. Chunking: Split documents into 500-token chunks with 50-token overlap.3. Embeddings: Use OpenAI text-embedding-3-small. Store vectors in Pinecone (free tier) or Weaviate (Docker).4. Retrieval: Build search endpoint: query → embedding → top-5 similar chunks.5. Generation: Send chunks + query to GPT-4o with system prompt: \"Answer using only the provided context. Cite sources.\"6. Frontend: Next.js chat UI with streaming (SSE or Vercel AI SDK).7. Deploy: Dockerize + deploy to AWS/GCP or Railway/Render.",
                    "key concepts": [
                        "Vector similarity search",
                        "Chunking strategies (fixed, semantic, recursive)",
                        "Streaming responses",
                        "Source citation and grounding",
                        "Conversation memory"
                    ],
                    "resources": [
                        "Pinecone Docs",
                        "LangChain JS Docs",
                        "Vercel AI SDK",
                        "YouTube: \"Build RAG from Scratch\""
                    ]
                }
            },
            {
                "id": "imm-5",
                "title": "AI Agent Workflow Tool",
                "desc": "LangChain/LangGraph multi-step agent. Show reasoning + tool use.",
                "tags": [
                    "Portfolio"
                ],
                "guide": {
                    "goal": "Build an AI agent that can perform multi-step tasks using tools (search, calculator, database query) with visible reasoning steps.",
                    "build this": "Step-by-Step:1. Define Tools: 3 tools — (a) web search (Serper.dev), (b) calculator, (c) weather API.2. Agent Loop: Use LangGraph ReAct agent: LLM thinks → picks tool → executes → observes → repeats.3. State Management: Track steps in state graph. Show user: \"Step 1: Searching...\"4. Human-in-the-loop: Approval gates for expensive actions.5. Persistence: Save runs to PostgreSQL.6. UI: Stream reasoning steps in real-time (WebSocket/SSE).",
                    "key concepts": [
                        "ReAct pattern (reasoning + acting)",
                        "Tool definition and function calling",
                        "State machines with LangGraph",
                        "Human approval workflows",
                        "Real-time streaming"
                    ],
                    "resources": [
                        "LangGraph Documentation",
                        "LangChain Agents Docs",
                        "ReAct paper (reasoning + acting)"
                    ]
                }
            },
            {
                "id": "imm-6",
                "title": "Deploy with Docker + CI/CD",
                "desc": "Containerize your AI app. GitHub Actions → AWS/GCP.",
                "tags": [
                    "Infra"
                ],
                "guide": {
                    "goal": "Dockerize your RAG or Agent project and set up automated deployment so every git push builds, tests, and deploys automatically.",
                    "build this": "Step-by-Step:1. Dockerfile: Multi-stage build for Node.js/Python. Separate build and runtime stages.2. Docker Compose: Local dev stack: app + PostgreSQL + Redis + Weaviate.3. GitHub Actions: lint → test → build Docker → push to ECR → deploy to ECS.4. Environment: AWS Secrets Manager for API keys. Never commit .env.5. Health Checks: Add /health endpoint. Configure LB health checks.6. Rollback: Tag images with commit SHA. Keep last 5 versions.",
                    "key concepts": [
                        "Multi-stage Docker builds",
                        "Docker Compose orchestration",
                        "GitHub Actions workflows",
                        "Container registries (ECR, GCR)",
                        "Health checks and zero-downtime deploys"
                    ],
                    "resources": [
                        "Docker Getting Started",
                        "GitHub Actions Docs",
                        "AWS ECS Tutorial"
                    ]
                }
            }
        ]
    },
    {
        "id": "phase1",
        "badge": "1",
        "title": "Phase 1 — Backend & Systems Foundation",
        "subtitle": "Month 1-4 | Java, Spring Boot, DSA, Linux, Docker",
        "items": [
            {
                "id": "p1-1",
                "title": "OOP, Collections, Generics, Streams",
                "desc": "Core language features. Use AI to generate practice problems.",
                "tags": [
                    "Core"
                ],
                "guide": {
                    "goal": "Write Java fluently: classes, inheritance, interfaces, lambda expressions, Stream API, and generic types. Be comfortable reading any Java codebase.",
                    "build this": "Build a Library Management System CLI app: Books, Members, Loans. Use Collections (ArrayList, HashMap), Streams for filtering/sorting, and Generics for a generic Repository pattern.",
                    "key concepts": [
                        "Classes, Objects, Encapsulation, Inheritance, Polymorphism",
                        "Abstract classes vs Interfaces (Java 8+ default methods)",
                        "Collections Framework: List, Set, Map, Queue",
                        "Streams: filter, map, reduce, collect, parallel streams",
                        "Generics: Type parameters, bounded types, wildcards",
                        "Optional class for null-safety"
                    ],
                    "resources": [
                        "Helsinki MOOC (Java I & II) — Free",
                        "\"Java: The Complete Reference\" by Herbert Schildt",
                        "Practice: Exercism Java Track"
                    ]
                }
            },
            {
                "id": "p1-2",
                "title": "Concurrency & Multithreading",
                "desc": "Executors, CompletableFuture, synchronized, volatile",
                "tags": [
                    "Hard"
                ],
                "guide": {
                    "goal": "Understand how to write thread-safe Java code, use high-level concurrency utilities, and debug race conditions.",
                    "build this": "Build a Rate Limiter and a Thread Pool Web Crawler. Crawler fetches 100 URLs concurrently using ExecutorService, respects robots.txt, saves thread-safely.",
                    "key concepts": [
                        "Thread lifecycle, Runnable vs Callable",
                        "ExecutorService, ThreadPoolExecutor, ForkJoinPool",
                        "CompletableFuture: chaining, combining, exception handling",
                        "synchronized, ReentrantLock, ReadWriteLock",
                        "Atomic classes (AtomicInteger, AtomicReference)",
                        "volatile, happens-before relationship",
                        "Concurrent collections: ConcurrentHashMap, BlockingQueue"
                    ],
                    "resources": [
                        "\"Java Concurrency in Practice\" by Goetz (Ch 1-8, 10)",
                        "Oracle Concurrency Tutorial",
                        "YouTube: \"Java Multithreading\" by Jakob Jenkov"
                    ]
                }
            },
            {
                "id": "p1-3",
                "title": "JVM Internals & Memory Management",
                "desc": "GC types, heap structure, tuning basics. Critical for debugging.",
                "tags": [
                    "Deep"
                ],
                "guide": {
                    "goal": "Understand how Java memory works, how to read GC logs, and how to diagnose OutOfMemoryError in production.",
                    "build this": "Create a Memory Leak Demo App that intentionally leaks memory. Use VisualVM and JVM flags to detect, analyze, and fix it. Generate heap dump and analyze with Eclipse MAT.",
                    "key concepts": [
                        "JVM architecture: Classloader, Runtime Data Areas, Execution Engine",
                        "Heap: Young (Eden, S0, S1) vs Old generation",
                        "Garbage Collectors: G1GC, ZGC, Shenandoah",
                        "GC logs: -Xlog:gc*, reading pause times",
                        "Heap dumps and thread dumps",
                        "JVM flags: -Xms, -Xmx, -XX:+UseG1GC",
                        "Memory leaks: static collections, listeners, ThreadLocal"
                    ],
                    "resources": [
                        "\"Java Performance\" by Scott Oaks (Ch 4-6)",
                        "Oracle GC Tuning Guide",
                        "YouTube: \"JVM Memory Management\" by Java Brains"
                    ]
                }
            },
            {
                "id": "p1-4",
                "title": "Spring Boot Core — REST APIs, DI, AOP",
                "desc": "Build production-grade APIs. Let AI write controllers.",
                "tags": [
                    "Core"
                ],
                "guide": {
                    "goal": "Build REST APIs with proper layering (Controller → Service → Repository), understand Dependency Injection, and use AOP for cross-cutting concerns.",
                    "build this": "Build an E-Commerce API: Products, Orders, Users, Cart. Use proper DTOs, validation, global exception handling, and logging. Add Swagger/OpenAPI docs.",
                    "key concepts": [
                        "@RestController, @RequestMapping, @GetMapping/@PostMapping",
                        "@Autowired vs Constructor Injection (prefer constructor)",
                        "@Component, @Service, @Repository stereotypes",
                        "ApplicationContext, Bean lifecycle, @Scope",
                        "@Configuration, @Bean, @Profile",
                        "AOP: @Aspect, @Before, @After, @Around for logging/metrics",
                        "Spring Boot auto-configuration"
                    ],
                    "resources": [
                        "Spring.io Guides",
                        "\"Spring Boot in Practice\" by Somnath Musib",
                        "Udemy: \"Spring Boot 3 & Spring Framework 6\" by Chad Darby"
                    ]
                }
            },
            {
                "id": "p1-5",
                "title": "Spring Data JPA & Hibernate",
                "desc": "Complex queries, transactions, lazy loading, N+1 fixes",
                "tags": [
                    "Core"
                ],
                "guide": {
                    "goal": "Master database access in Spring: entity mapping, relationships, custom queries, pagination, and performance optimization.",
                    "build this": "Extend your E-Commerce API with complex queries: search products by multiple filters (category, price range, rating), pagination, sorting. Implement reporting dashboard with @Query native SQL.",
                    "key concepts": [
                        "@Entity, @Table, @Id, @GeneratedValue",
                        "Relationships: @OneToOne, @OneToMany, @ManyToMany",
                        "FetchType.LAZY vs EAGER (always prefer LAZY)",
                        "N+1 problem and solutions: EntityGraph, JOIN FETCH",
                        "@Query, @Modifying, native queries",
                        "Specification API for dynamic queries",
                        "@Transactional, propagation, isolation levels",
                        "Optimistic locking with @Version"
                    ],
                    "resources": [
                        "Spring Data JPA Reference",
                        "\"High-Performance Java Persistence\" by Vlad Mihalcea",
                        "YouTube: Vlad Mihalcea's Hibernate tutorials"
                    ]
                }
            },
            {
                "id": "p1-6",
                "title": "Spring Security — JWT, OAuth2",
                "desc": "Authentication, authorization, role-based access",
                "tags": [
                    "Must"
                ],
                "guide": {
                    "goal": "Secure Spring Boot APIs with JWT tokens and OAuth2. Understand the security filter chain and how to customize it.",
                    "build this": "Add full auth to your E-Commerce API: register/login with JWT, role-based access (ADMIN, CUSTOMER), password reset flow, and OAuth2 login with Google/GitHub.",
                    "key concepts": [
                        "SecurityFilterChain, AuthenticationManager",
                        "JWT: generation, validation, refresh tokens",
                        "Password encoding with BCrypt",
                        "Role-based access: @PreAuthorize, @Secured",
                        "OAuth2: authorization code flow, resource server",
                        "CORS configuration",
                        "Method-level vs URL-level security"
                    ],
                    "resources": [
                        "Spring Security Reference",
                        "\"Spring Security in Action\" by Laurentiu Spilca",
                        "GitHub: Spring Security Samples"
                    ]
                }
            },
            {
                "id": "p1-7",
                "title": "Spring Boot Testing",
                "desc": "Unit, integration, MockMvc, Testcontainers",
                "tags": [
                    "Core"
                ],
                "guide": {
                    "goal": "Write comprehensive tests: unit tests with mocks, integration tests with real database, and API tests with MockMvc.",
                    "build this": "Achieve 80%+ code coverage on your E-Commerce API. Write tests for happy paths, edge cases, and security scenarios. Use Testcontainers for PostgreSQL integration tests.",
                    "key concepts": [
                        "JUnit 5: @Test, @BeforeEach, parameterized tests",
                        "Mockito: @Mock, @InjectMocks, when/then, verify",
                        "@SpringBootTest, @WebMvcTest, @DataJpaTest",
                        "MockMvc: perform GET/POST, assert status/jsonPath",
                        "Testcontainers: PostgreSQL, Redis in Docker for tests",
                        "@Sql for database setup in tests"
                    ],
                    "resources": [
                        "Spring Boot Testing Docs",
                        "Testcontainers Docs",
                        "\"Unit Testing Principles\" by Vladimir Khorikov"
                    ]
                }
            },
            {
                "id": "p1-8",
                "title": "Advanced SQL — CTEs, Window Functions, Indexing",
                "desc": "Query optimization, execution plans, EXPLAIN ANALYZE",
                "tags": [
                    "Must"
                ],
                "guide": {
                    "goal": "Write complex SQL queries for analytics and reporting. Read execution plans and optimize slow queries.",
                    "build this": "Create an Analytics Dashboard Backend for your E-Commerce app: monthly revenue, top products, customer cohort retention, running totals — all using raw SQL.",
                    "key concepts": [
                        "CTEs (Common Table Expressions): recursive and non-recursive",
                        "Window functions: ROW_NUMBER, RANK, LEAD, LAG, SUM() OVER",
                        "Indexes: B-Tree, partial, composite, covering indexes",
                        "EXPLAIN ANALYZE: sequential scan vs index scan, cost estimation",
                        "Query rewriting for performance",
                        "Partitioning strategies"
                    ],
                    "resources": [
                        "Mode Analytics SQL Tutorial (advanced)",
                        "SQLBolt for basics",
                        "\"SQL Performance Explained\" by Markus Winand",
                        "Practice: LeetCode Database"
                    ]
                }
            },
            {
                "id": "p1-9",
                "title": "PostgreSQL Deep Dive",
                "desc": "JSONB, Full-text search, Partitioning, Replication",
                "tags": [
                    "Core"
                ],
                "guide": {
                    "goal": "Use PostgreSQL as more than a relational store: JSON documents, full-text search, and advanced features.",
                    "build this": "Add a Product Catalog with JSONB (flexible product attributes) and a Full-Text Search endpoint that searches products by name, description, and tags with ranking.",
                    "key concepts": [
                        "JSONB operators: ->, ->>, @>, ?",
                        "Full-text search: tsvector, tsquery, GIN indexes",
                        "Partitioning: range, list, hash partitions",
                        "Replication: streaming replication, logical replication",
                        "Listen/Notify for real-time events",
                        "Custom data types and extensions (PostGIS, pgvector)"
                    ],
                    "resources": [
                        "PostgreSQL Official Docs",
                        "\"PostgreSQL Up & Running\" by Regina Obe",
                        "PGExercises"
                    ]
                }
            },
            {
                "id": "p1-10",
                "title": "Database Design & Normalization",
                "desc": "Schema design, ACID, CAP theorem basics",
                "tags": [
                    "Core"
                ],
                "guide": {
                    "goal": "Design schemas that scale, avoid common anti-patterns, and understand trade-offs in data modeling.",
                    "build this": "Design a Social Media Database Schema: users, posts, comments, likes, follows, messages. Handle read-heavy vs write-heavy trade-offs. Compare normalized vs denormalized approaches.",
                    "key concepts": [
                        "Normal Forms: 1NF, 2NF, 3NF, BCNF (know when to break them)",
                        "ACID properties and isolation levels",
                        "CAP Theorem: Consistency vs Availability vs Partition Tolerance",
                        "Indexing strategy for read-heavy vs write-heavy workloads",
                        "Soft deletes vs hard deletes",
                        "Audit trails and temporal tables"
                    ],
                    "resources": [
                        "\"Database Design for Mere Mortals\" by Hernandez",
                        "\"Designing Data-Intensive Applications\" Chapters 2, 5, 7",
                        "dbdiagram.io — practice drawing ER diagrams"
                    ]
                }
            },
            {
                "id": "p1-11",
                "title": "Linux System Administration",
                "desc": "Process management, networking, systemd, shell scripting",
                "tags": [
                    "Core"
                ],
                "guide": {
                    "goal": "Be comfortable on a Linux server. Manage processes, debug networking, automate tasks with bash, and configure services.",
                    "build this": "Setup a VPS from scratch (AWS EC2 t2.micro or DigitalOcean): create users, harden SSH, configure firewall (ufw), install Java/Node/PostgreSQL, deploy your Spring Boot app, and write a backup script.",
                    "key concepts": [
                        "File system: /etc, /var, /opt, /home, permissions (chmod, chown)",
                        "Process management: ps, top, htop, kill, nice",
                        "Networking: netstat, ss, curl, tcpdump, iptables/ufw",
                        "systemd: service files, journalctl, timers",
                        "Shell scripting: variables, loops, functions, error handling",
                        "Package management: apt, dnf",
                        "SSH key management, fail2ban"
                    ],
                    "resources": [
                        "Linux Journey (free, interactive)",
                        "\"The Linux Command Line\" by William Shotts (free PDF)",
                        "OverTheWire: Bandit"
                    ]
                }
            },
            {
                "id": "p1-12",
                "title": "Docker — Containers, Compose, Networking",
                "desc": "Multi-stage builds, volume management, container orchestration prep",
                "tags": [
                    "Cloud"
                ],
                "guide": {
                    "goal": "Containerize applications, manage multi-container environments, and understand Docker networking and storage.",
                    "build this": "Dockerize your entire E-Commerce stack: Spring Boot app, PostgreSQL, Redis (for caching), Nginx. Use Docker Compose for local dev. Write a multi-stage Dockerfile that builds in 2 minutes and runs in under 200MB.",
                    "key concepts": [
                        "Dockerfile instructions: FROM, RUN, COPY, CMD, ENTRYPOINT",
                        "Multi-stage builds (build stage + runtime stage)",
                        "Layer caching optimization (order matters)",
                        "Docker Compose: services, networks, volumes, depends_on",
                        "Docker networking: bridge, host, overlay",
                        "Volume types: bind mounts, named volumes, tmpfs",
                        "Docker Hub vs private registry (ECR)"
                    ],
                    "resources": [
                        "Docker Getting Started",
                        "\"Docker Deep Dive\" by Nigel Poulton",
                        "Awesome Docker"
                    ]
                }
            },
            {
                "id": "p1-13",
                "title": "Nginx & Reverse Proxy Mastery",
                "desc": "Load balancing, SSL, rate limiting, caching layers",
                "tags": [
                    "Core"
                ],
                "guide": {
                    "goal": "Use Nginx as a reverse proxy, load balancer, and caching layer in front of your applications.",
                    "build this": "Configure Nginx as a reverse proxy for your Dockerized Spring Boot app. Add SSL with Let's Encrypt (certbot), configure rate limiting (10 req/sec per IP), and static file caching.",
                    "key concepts": [
                        "Reverse proxy: proxy_pass, upstream",
                        "Load balancing: round-robin, least_conn, ip_hash",
                        "SSL/TLS: certificate generation, HTTPS redirect, HSTS",
                        "Rate limiting: limit_req_zone, burst, nodelay",
                        "Caching: proxy_cache, cache keys, cache invalidation",
                        "Gzip compression",
                        "Location blocks and regex matching"
                    ],
                    "resources": [
                        "Nginx Official Docs",
                        "\"Nginx HTTP Server\" by Clément Nedelcu",
                        "DigitalOcean Nginx Tutorials"
                    ]
                }
            },
            {
                "id": "p1-14",
                "title": "DSA for System Design Interviews",
                "desc": "Trees, Graphs, DP, Greedy. Focus on patterns, not memorization.",
                "tags": [
                    "Interview"
                ],
                "guide": {
                    "goal": "Solve LeetCode medium problems in 20-30 minutes. Recognize patterns and apply the right data structure instantly.",
                    "build this": "Follow NeetCode 150 roadmap. Do 2-3 problems daily. Focus on: Arrays, Two Pointers, Sliding Window, Stack, Binary Search, Linked List, Trees, Heap, Backtracking, Graphs, DP.",
                    "key concepts": [
                        "Two Pointers: sorted arrays, palindromes",
                        "Sliding Window: subarray problems",
                        "Fast & Slow Pointers: cycle detection",
                        "Merge Intervals: overlapping ranges",
                        "Cyclic Sort: finding missing/duplicate numbers",
                        "Tree BFS/DFS: level order, recursion",
                        "Graph: BFS, DFS, Dijkstra, Union-Find",
                        "DP: 0/1 Knapsack, unbounded, LCS"
                    ],
                    "resources": [
                        "NeetCode 150 Roadmap",
                        "LeetCode (premium for company-tagged)",
                        "\"Cracking the Coding Interview\" by Gayle McDowell"
                    ]
                }
            }
        ]
    },
    {
        "id": "phase2",
        "badge": "2",
        "title": "Phase 2 — AI Application Engineering",
        "subtitle": "Month 2-6 | LLMs, RAG, Agents, Vector DBs, Python",
        "items": [
            {
                "id": "p2-1",
                "title": "Python Basics for AI Work",
                "desc": "Syntax, data structures, pandas, numpy. You don't need to be a Python expert.",
                "tags": [
                    "Core"
                ],
                "guide": {
                    "goal": "Be productive in Python for AI/ML tasks within 2 weeks. You don't need deep CS knowledge — you need to glue APIs and process data.",
                    "build this": "Write a Data Processing Pipeline that reads a CSV, cleans data with pandas, generates summary statistics, and outputs a formatted report. Then add a script that calls OpenAI API to summarize the report.",
                    "key concepts": [
                        "Data types: lists, dicts, sets, tuples, comprehensions",
                        "Functions, classes, modules, virtual environments",
                        "pandas: DataFrame, filtering, groupby, merge",
                        "numpy: arrays, broadcasting, basic operations",
                        "File I/O: CSV, JSON, reading APIs",
                        "asyncio basics (for concurrent API calls)"
                    ],
                    "resources": [
                        "Automate the Boring Stuff with Python (free)",
                        "pandas Documentation",
                        "\"Python for Data Analysis\" by Wes McKinney"
                    ]
                }
            },
            {
                "id": "p2-2",
                "title": "FastAPI for AI Backend Services",
                "desc": "Async endpoints, dependency injection, OpenAPI docs. Better than Flask for AI.",
                "tags": [
                    "Must"
                ],
                "guide": {
                    "goal": "Build high-performance async Python APIs. FastAPI is the industry standard for AI microservices in 2026.",
                    "build this": "Build an AI Service API: /summarize, /translate, /classify endpoints. Each calls an LLM asynchronously. Add request validation with Pydantic, auto-generated docs, and rate limiting.",
                    "key concepts": [
                        "Path operations: @app.get, @app.post, async def",
                        "Pydantic models for request/response validation",
                        "Dependency injection: Depends()",
                        "Background tasks for non-blocking operations",
                        "WebSockets for streaming responses",
                        "Middleware: CORS, logging, rate limiting",
                        "Testing: TestClient, pytest-asyncio"
                    ],
                    "resources": [
                        "FastAPI Official Docs (best docs in Python)",
                        "\"Building Data Science Applications with FastAPI\" by François Voron"
                    ]
                }
            },
            {
                "id": "p2-3",
                "title": "OpenAI / Anthropic / Gemini APIs",
                "desc": "Streaming, function calling, batch processing, rate limit handling",
                "tags": [
                    "AI Core"
                ],
                "guide": {
                    "goal": "Integrate multiple LLM providers robustly: handle errors, retries, rate limits, and cost optimization across OpenAI, Anthropic, and Google.",
                    "build this": "Build a Universal LLM Gateway: single API that routes to OpenAI, Claude, or Gemini based on model name. Implement fallback (if OpenAI fails, try Claude), streaming, and usage tracking.",
                    "key concepts": [
                        "Chat Completions API vs Assistants API",
                        "Streaming: Server-Sent Events (SSE) handling",
                        "Function calling / Tool use: defining schemas, parsing results",
                        "Rate limiting: exponential backoff, token bucket",
                        "Batch API for large-scale processing",
                        "Model selection: cost vs quality trade-offs",
                        "API key rotation and cost monitoring"
                    ],
                    "resources": [
                        "OpenAI Platform Docs",
                        "Anthropic API Docs",
                        "Google AI Studio / Gemini Docs",
                        "LiteLLM (unified LLM interface)"
                    ]
                }
            },
            {
                "id": "p2-4",
                "title": "Prompt Engineering & Structured Output",
                "desc": "JSON mode, system prompts, few-shot, chain-of-thought. Critical skill.",
                "tags": [
                    "AI Core"
                ],
                "guide": {
                    "goal": "Craft prompts that reliably produce structured, parseable output. This is the most important soft skill in AI engineering.",
                    "build this": "Build a Structured Data Extractor: input = messy unstructured text (email, invoice, resume), output = clean JSON with exact schema. Test with 50 real inputs and measure extraction accuracy.",
                    "key concepts": [
                        "System prompts: role definition, constraints, output format",
                        "Few-shot prompting: provide examples in context",
                        "Chain-of-Thought: \"Let's think step by step\"",
                        "JSON mode / Structured Output (OpenAI response_format)",
                        "Prompt versioning and A/B testing",
                        "Context window management: summarization, sliding window",
                        "Prompt injection prevention"
                    ],
                    "resources": [
                        "OpenAI Prompt Engineering Guide",
                        "Prompt Engineering Guide (DAIR)",
                        "\"The Art of Prompt Engineering\" by DataCamp"
                    ]
                }
            },
            {
                "id": "p2-5",
                "title": "Local LLMs — Ollama, vLLM, Llama.cpp",
                "desc": "Run models locally for privacy, cost, and offline scenarios",
                "tags": [
                    "AI Core"
                ],
                "guide": {
                    "goal": "Run open-source LLMs locally for privacy-sensitive applications, cost reduction, and offline environments.",
                    "build this": "Setup a Local AI Server with Ollama serving Llama 3.1, Mistral, and a coding model (CodeLlama). Build a simple chat UI that can switch between local and cloud models. Compare latency and quality.",
                    "key concepts": [
                        "Ollama: model management, Modelfile customization",
                        "Quantization: Q4_K_M, Q5_K_M, impact on quality",
                        "vLLM: high-throughput serving with PagedAttention",
                        "Llama.cpp: running on CPU, GGUF format",
                        "Hardware requirements: VRAM, RAM, CPU inference",
                        "Local RAG with Ollama + Chroma/Weaviate"
                    ],
                    "resources": [
                        "Ollama Website & Docs",
                        "vLLM GitHub",
                        "Llama.cpp GitHub",
                        "Hugging Face Model Cards for Llama, Mistral"
                    ]
                }
            },
            {
                "id": "p2-6",
                "title": "Vector DBs — Pinecone, Weaviate, Chroma, Qdrant",
                "desc": "Embedding storage, similarity search, hybrid search, metadata filtering",
                "tags": [
                    "AI Core"
                ],
                "guide": {
                    "goal": "Choose and use the right vector database for your use case. Understand trade-offs between managed, self-hosted, and embedded options.",
                    "build this": "Build a Vector DB Comparison Tool: same dataset (10K documents) loaded into Pinecone, Weaviate, and Chroma. Compare: ingestion speed, query latency, hybrid search quality, and filtering capabilities.",
                    "key concepts": [
                        "Vector similarity: cosine, Euclidean, dot product",
                        "Approximate Nearest Neighbor (ANN): HNSW, IVF",
                        "Pinecone: managed, metadata filtering, namespaces",
                        "Weaviate: GraphQL interface, modular AI integrations",
                        "Chroma: embedded, simple, good for prototyping",
                        "Qdrant: Rust-based, high performance, filtering",
                        "Hybrid search: vector + keyword (BM25)"
                    ],
                    "resources": [
                        "Pinecone Docs",
                        "Weaviate Docs",
                        "Chroma Docs",
                        "Qdrant Docs"
                    ]
                }
            },
            {
                "id": "p2-7",
                "title": "Embedding Models & Chunking Strategies",
                "desc": "OpenAI, Cohere, open-source embeddings. Semantic vs lexical chunking.",
                "tags": [
                    "AI Core"
                ],
                "guide": {
                    "goal": "Understand how text is converted to vectors and how document chunking affects retrieval quality.",
                    "build this": "Build a Chunking Evaluator: take 10 documents, chunk them with 5 different strategies (fixed size, semantic, recursive, paragraph, sentence). For each strategy, measure retrieval accuracy on 20 test questions.",
                    "key concepts": [
                        "Embedding models: text-embedding-3-large, Cohere embed-v3, BGE, E5",
                        "Chunking: fixed-size, recursive, semantic (NLTK/spaCy), agentic",
                        "Chunk size trade-off: context vs precision",
                        "Overlap: maintaining continuity between chunks",
                        "Multi-modal embeddings (images, audio)",
                        "Embedding dimensionality and quantization"
                    ],
                    "resources": [
                        "OpenAI Embeddings Guide",
                        "Cohere Embed Docs",
                        "MTEB Leaderboard"
                    ]
                }
            },
            {
                "id": "p2-8",
                "title": "Advanced RAG Patterns",
                "desc": "Multi-query, reranking, contextual compression, self-RAG, corrective RAG",
                "tags": [
                    "Deep"
                ],
                "guide": {
                    "goal": "Go beyond basic RAG. Implement advanced patterns that significantly improve answer quality and reduce hallucinations.",
                    "build this": "Upgrade your RAG Chatbot with all advanced patterns: multi-query expansion, Cohere reranking, contextual compression, and self-evaluation (LLM checks if answer is supported by context).",
                    "key concepts": [
                        "Multi-query: generate 3 variations of user question, retrieve for all",
                        "Reranking: cross-encoder (Cohere rerank) to reorder results",
                        "Contextual compression: summarize chunks before sending to LLM",
                        "Self-RAG: LLM evaluates if retrieval is sufficient",
                        "Corrective RAG: fallback to web search if no good chunks",
                        "Hypothetical Document Embedding (HyDE)",
                        "Query transformation: decomposition, step-back"
                    ],
                    "resources": [
                        "LangChain Advanced RAG Blog",
                        "Self-RAG Paper (Asai et al.)",
                        "Cohere Rerank Docs"
                    ]
                }
            },
            {
                "id": "p2-9",
                "title": "LangChain Core — Chains, Memory, Tools",
                "desc": "LCEL, memory management, tool integration, output parsers",
                "tags": [
                    "AI Core"
                ],
                "guide": {
                    "goal": "Use LangChain as a framework for building LLM applications with proper abstractions for chaining, memory, and tool use.",
                    "build this": "Build a Customer Support Bot using LangChain: retrieves from FAQ vector DB, uses conversation memory, escalates to human if confidence is low, and logs all interactions.",
                    "key concepts": [
                        "LCEL (LangChain Expression Language): pipe operators, runnable sequences",
                        "Chains: LLMChain, RetrievalQA, ConversationalRetrievalChain",
                        "Memory: ConversationBufferMemory, summary memory, vector memory",
                        "Tools: @tool decorator, StructuredTool, tool calling",
                        "Output parsers: PydanticOutputParser, JSON parser",
                        "Callbacks: tracing, logging, cost tracking"
                    ],
                    "resources": [
                        "LangChain Python Docs",
                        "LangChain JS Docs",
                        "LangChain Academy (free courses)"
                    ]
                }
            },
            {
                "id": "p2-10",
                "title": "LangGraph — State Machines & Agents",
                "desc": "Multi-agent workflows, conditional edges, persistence, human-in-the-loop",
                "tags": [
                    "Deep"
                ],
                "guide": {
                    "goal": "Build complex agent workflows as state machines with persistence, branching logic, and human approval gates.",
                    "build this": "Build a Research Assistant Agent: takes topic → plans sub-topics → searches web for each → summarizes → writes report → human reviews → publishes. All steps are nodes in a LangGraph with conditional edges.",
                    "key concepts": [
                        "StateGraph: nodes, edges, conditional edges",
                        "State schema: TypedDict, Pydantic models",
                        "Persistence: checkpointer (PostgreSQL, Redis, SQLite)",
                        "Human-in-the-loop: interrupt, approval, edit",
                        "Subgraphs: modular agent components",
                        "Time-travel: replay, fork, edit past states",
                        "Multi-agent: supervisor pattern, direct communication"
                    ],
                    "resources": [
                        "LangGraph Documentation",
                        "LangGraph Studio (visual editor)",
                        "GitHub: LangGraph examples repo"
                    ]
                }
            },
            {
                "id": "p2-11",
                "title": "Agent Architecture — ReAct, Plan & Execute",
                "desc": "Tool use, reasoning loops, error recovery, observability",
                "tags": [
                    "AI Core"
                ],
                "guide": {
                    "goal": "Understand how AI agents reason, use tools, and recover from errors. Build agents that don't get stuck in infinite loops.",
                    "build this": "Build a Code Review Agent: takes a PR diff → analyzes for bugs → checks against style guide → suggests fixes → creates review comments. Uses GitHub API as a tool.",
                    "key concepts": [
                        "ReAct pattern: Reason → Act → Observe → Repeat",
                        "Plan & Execute: separate planning from execution",
                        "Tool definition: name, description, parameters (JSON schema)",
                        "Max iteration limits and escape hatches",
                        "Error handling: tool failure → fallback → human handoff",
                        "Agent observability: trace every thought and action"
                    ],
                    "resources": [
                        "ReAct Paper (Yao et al.)",
                        "LangChain Agent Observability",
                        "GitHub: AutoGPT (study architecture)"
                    ]
                }
            },
            {
                "id": "p2-12",
                "title": "AI Workflow Automation",
                "desc": "n8n, Make.com, or custom pipelines. Connect AI to business processes.",
                "tags": [
                    "AI Core"
                ],
                "guide": {
                    "goal": "Automate business workflows by connecting AI to existing tools (CRM, email, Slack, databases) without writing code for every integration.",
                    "build this": "Build an AI Lead Qualification Pipeline: new lead enters CRM → AI researches company → scores lead → drafts personalized email → sends via Gmail → logs to Airtable → notifies Slack. Use n8n or build with Python + webhooks.",
                    "key concepts": [
                        "n8n: self-hosted workflow automation, 400+ integrations",
                        "Make.com (Integromat): visual workflow builder",
                        "Webhook triggers and API polling",
                        "Conditional logic and error branches",
                        "Custom nodes: writing your own integrations",
                        "Scheduling and cron jobs"
                    ],
                    "resources": [
                        "n8n Documentation",
                        "Make.com Help Center",
                        "YouTube: \"n8n Tutorial\" for practical workflows"
                    ]
                }
            },
            {
                "id": "p2-13",
                "title": "AI Observability & Evaluation",
                "desc": "LangSmith, prompt versioning, A/B testing, hallucination detection",
                "tags": [
                    "Deep"
                ],
                "guide": {
                    "goal": "Monitor AI systems in production: track prompts, measure accuracy, detect drift, and iterate based on real data.",
                    "build this": "Add full observability to your RAG app: LangSmith tracing for every query, user feedback collection (thumbs up/down), automatic evaluation on 100 test questions, and an alerting dashboard for hallucination spikes.",
                    "key concepts": [
                        "Tracing: spans, traces, metadata, tags",
                        "Prompt versioning: track changes, rollback",
                        "Evaluation metrics: relevance, faithfulness, answer similarity",
                        "Hallucination detection: self-consistency, NLI models",
                        "A/B testing: prompt variants, model variants",
                        "Cost tracking: tokens, latency, $ per query",
                        "Drift detection: embedding space monitoring"
                    ],
                    "resources": [
                        "LangSmith Documentation",
                        "RAGAS (RAG evaluation framework)",
                        "Helicone (open-source LLM observability)"
                    ]
                }
            },
            {
                "id": "p2-14",
                "title": "Production RAG Application",
                "desc": "Document ingestion, hybrid search, chat UI, feedback loop. Deployed live.",
                "tags": [
                    "Portfolio"
                ],
                "guide": {
                    "goal": "Build a production-grade RAG system that you can show to employers. It should handle real documents, real users, and real deployment.",
                    "build this": "Complete Architecture:Frontend: Next.js chat UI with streaming, markdown rendering, source citationsBackend API: FastAPI or Node.js — upload, chat, history, feedbackDocument Processing: PDF/DOCX parsing, chunking, embedding generationVector DB: Pinecone/Weaviate with metadata filteringLLM: OpenAI GPT-4o with fallback to local modelDatabase: PostgreSQL for chat history, user data, feedbackCache: Redis for session managementAuth: JWT or OAuth2Observability: LangSmith tracing, user feedback",
                    "key concepts": [
                        "Multi-document upload (drag & drop)",
                        "Conversational memory (previous Q&A context)",
                        "Source highlighting (show which chunk was used)",
                        "User feedback (thumbs up/down per response)",
                        "Conversation history sidebar",
                        "Export chat as PDF/Markdown",
                        "Admin dashboard: usage stats, popular questions"
                    ],
                    "resources": [
                        "Deploy with Docker + AWS ECS/GCP Cloud Run",
                        "Use GitHub Actions for CI/CD",
                        "Add monitoring with CloudWatch/Datadog",
                        "Custom domain + SSL"
                    ]
                }
            }
        ]
    },
    {
        "id": "phase3",
        "badge": "3",
        "title": "Phase 3 — Cloud Native & Distributed Systems",
        "subtitle": "Month 4-8 | K8s, AWS, CI/CD, Terraform, Kafka, Microservices",
        "items": [
            {
                "id": "p3-1",
                "title": "Kubernetes Core Concepts",
                "desc": "Pods, Services, Deployments, ConfigMaps, Secrets, Ingress",
                "tags": [
                    "Cloud"
                ],
                "guide": {
                    "goal": "Understand Kubernetes fundamentals and deploy containerized applications at scale.",
                    "build this": "Deploy your Dockerized E-Commerce app to a local Kubernetes cluster (minikube or kind). Create Deployments, Services, ConfigMaps, and an Ingress. Scale to 3 replicas and verify load balancing.",
                    "key concepts": [
                        "Pods, ReplicaSets, Deployments",
                        "Services: ClusterIP, NodePort, LoadBalancer",
                        "ConfigMaps and Secrets for configuration",
                        "Ingress and Ingress Controllers (nginx)",
                        "Namespaces for multi-tenancy",
                        "kubectl commands and resource management",
                        "Resource limits and requests (CPU/memory)"
                    ],
                    "resources": [
                        "Kubernetes Official Tutorials",
                        "\"Kubernetes Up & Running\" by Kelsey Hightower",
                        "KodeKloud (hands-on labs)"
                    ]
                }
            },
            {
                "id": "p3-2",
                "title": "K8s Advanced — Helm, Operators, CRDs",
                "desc": "Package management, custom resources, stateful workloads",
                "tags": [
                    "Deep"
                ],
                "guide": {
                    "goal": "Master advanced Kubernetes concepts for production environments.",
                    "build this": "Create a Helm Chart for your E-Commerce app. Write a simple Operator that watches for custom resources and auto-scales based on queue depth. Deploy a StatefulSet for PostgreSQL with persistent volumes.",
                    "key concepts": [
                        "Helm: charts, values, templates, releases",
                        "Operators: custom controllers, reconciliation loops",
                        "CRDs (Custom Resource Definitions)",
                        "StatefulSets: ordered deployment, stable network identity",
                        "DaemonSets, Jobs, CronJobs",
                        "PodDisruptionBudgets for availability",
                        "NetworkPolicies for security"
                    ],
                    "resources": [
                        "Helm Documentation",
                        "Kubernetes Operators",
                        "\"Programming Kubernetes\" by Michael Hausenblas"
                    ]
                }
            },
            {
                "id": "p3-3",
                "title": "K8s Networking & Storage",
                "desc": "CNI, PVCs, StatefulSets, network policies, service mesh intro",
                "tags": [
                    "Cloud"
                ],
                "guide": {
                    "goal": "Understand Kubernetes networking and storage for production workloads.",
                    "build this": "Setup a multi-tier app in K8s: frontend, API, cache, database. Configure internal networking between tiers, persistent storage for DB, and network policies to enforce zero-trust security.",
                    "key concepts": [
                        "CNI plugins: Calico, Cilium, Flannel",
                        "Persistent Volumes (PV) and Persistent Volume Claims (PVC)",
                        "Storage classes: local, EBS, NFS",
                        "Headless services for StatefulSets",
                        "DNS resolution within cluster",
                        "Service mesh intro: Istio, Linkerd concepts",
                        "mTLS and traffic splitting basics"
                    ],
                    "resources": [
                        "K8s Storage Docs",
                        "K8s Networking Docs",
                        "\"Kubernetes Networking\" by James Strong"
                    ]
                }
            },
            {
                "id": "p3-4",
                "title": "AWS Core Services",
                "desc": "EC2, S3, RDS, Lambda, IAM, VPC, CloudWatch. Pick one cloud, master it.",
                "tags": [
                    "Cloud"
                ],
                "guide": {
                    "goal": "Build infrastructure on AWS. Understand core services and how they connect. Get AWS Solutions Architect Associate certified.",
                    "build this": "Migrate your Dockerized E-Commerce app to AWS: EC2 for app servers, RDS for PostgreSQL, S3 for file storage, Lambda for image processing, CloudWatch for monitoring. Setup VPC with public/private subnets.",
                    "key concepts": [
                        "EC2: instance types, AMIs, security groups, key pairs",
                        "S3: buckets, versioning, lifecycle policies, CORS",
                        "RDS: PostgreSQL, backups, read replicas, parameter groups",
                        "Lambda: triggers, layers, concurrency limits",
                        "IAM: users, roles, policies, least privilege",
                        "VPC: subnets, route tables, NAT gateway, peering",
                        "CloudWatch: metrics, alarms, logs, dashboards"
                    ],
                    "resources": [
                        "AWS Getting Started",
                        "\"AWS Certified Solutions Architect\" by Stephane Maarek (Udemy)",
                        "AWS Architecture Center",
                        "AWS Free Tier for hands-on practice"
                    ]
                }
            },
            {
                "id": "p3-5",
                "title": "AWS AI/ML Services",
                "desc": "Bedrock, SageMaker, OpenSearch. Managed AI infrastructure.",
                "tags": [
                    "AI Infra"
                ],
                "guide": {
                    "goal": "Use AWS managed AI services instead of building everything from scratch. Understand when to use managed vs self-hosted.",
                    "build this": "Build an AI Document Processor on AWS: documents uploaded to S3 trigger Lambda → Textract extracts text → Bedrock (Claude) summarizes → results stored in DynamoDB → frontend reads via API Gateway.",
                    "key concepts": [
                        "Bedrock: foundation models, fine-tuning, agents",
                        "SageMaker: training, deployment, endpoints",
                        "OpenSearch: vector search, hybrid search",
                        "Textract: OCR, form extraction",
                        "Comprehend: sentiment, entity detection",
                        "Rekognition: image/video analysis",
                        "Cost comparison: managed vs self-hosted"
                    ],
                    "resources": [
                        "AWS Bedrock Docs",
                        "SageMaker Docs",
                        "AWS AI/ML Blog for patterns"
                    ]
                }
            },
            {
                "id": "p3-6",
                "title": "Serverless & Event-Driven Architecture",
                "desc": "Lambda, EventBridge, SQS, SNS. Cost-efficient scaling patterns.",
                "tags": [
                    "Cloud"
                ],
                "guide": {
                    "goal": "Build event-driven systems that scale to zero and handle massive load without managing servers.",
                    "build this": "Build an Order Processing System: API Gateway → Lambda validates order → EventBridge routes to SQS → Lambda processes payment → SNS notifies customer → DynamoDB stores result. All serverless, auto-scaling.",
                    "key concepts": [
                        "Lambda: cold starts, provisioned concurrency, layers",
                        "EventBridge: rules, buses, event patterns, scheduling",
                        "SQS: standard vs FIFO, visibility timeout, DLQ",
                        "SNS: topics, subscriptions, fan-out",
                        "Step Functions: state machines, error handling",
                        "API Gateway: REST vs HTTP vs WebSocket APIs",
                        "DynamoDB: single-table design, GSIs, streams"
                    ],
                    "resources": [
                        "Lambda Docs",
                        "EventBridge Docs",
                        "\"Serverless Architectures on AWS\" by Peter Sbarski"
                    ]
                }
            },
            {
                "id": "p3-7",
                "title": "GitHub Actions / GitLab CI",
                "desc": "Build, test, deploy pipelines. Matrix builds, secrets management.",
                "tags": [
                    "Cloud"
                ],
                "guide": {
                    "goal": "Automate your entire software delivery pipeline: from code commit to production deployment.",
                    "build this": "Build a complete CI/CD pipeline for your E-Commerce app: on push → run tests → build Docker image → push to ECR → deploy to ECS → run smoke tests → notify Slack. Include matrix builds for Node.js and Java versions.",
                    "key concepts": [
                        "Workflow syntax: on, jobs, steps, runs-on",
                        "Actions marketplace: checkout, setup-node, docker-build-push",
                        "Matrix builds: testing across versions",
                        "Secrets and environment variables",
                        "Artifacts and caching for speed",
                        "Reusable workflows and composite actions",
                        "Approval gates and environments"
                    ],
                    "resources": [
                        "GitHub Actions Docs",
                        "GitLab CI Docs",
                        "\"GitHub Actions in Action\" by Michael Heap"
                    ]
                }
            },
            {
                "id": "p3-8",
                "title": "Terraform / Pulumi",
                "desc": "IaC for AWS/K8s. State management, modules, workspaces.",
                "tags": [
                    "Cloud"
                ],
                "guide": {
                    "goal": "Define your entire infrastructure as code. Version control your infrastructure and deploy consistently across environments.",
                    "build this": "Write Terraform modules for your E-Commerce infrastructure: VPC module, ECS module, RDS module, S3 module. Use workspaces for dev/staging/prod. Store state in S3 with DynamoDB locking.",
                    "key concepts": [
                        "Terraform syntax: providers, resources, variables, outputs",
                        "Modules: reusable, composable infrastructure components",
                        "State management: local vs remote (S3), locking",
                        "Workspaces: environment separation",
                        "Plan and apply workflow",
                        "Pulumi alternative: TypeScript/Python for IaC",
                        "Importing existing resources",
                        "Drift detection and remediation"
                    ],
                    "resources": [
                        "Terraform Docs",
                        "Pulumi Docs",
                        "\"Terraform: Up & Running\" by Yevgeniy Brikman"
                    ]
                }
            },
            {
                "id": "p3-9",
                "title": "ArgoCD / Flux — GitOps",
                "desc": "Declarative deployments, drift detection, rollback strategies",
                "tags": [
                    "Deep"
                ],
                "guide": {
                    "goal": "Implement GitOps: your Git repo is the single source of truth for what's running in production.",
                    "build this": "Setup ArgoCD for your K8s cluster. Configure it to watch your Git repo and auto-sync deployments. Implement a canary deployment strategy with Flagger. Add drift detection and automated rollback.",
                    "key concepts": [
                        "GitOps principles: declarative, versioned, automated",
                        "ArgoCD: applications, projects, sync policies",
                        "App of Apps pattern",
                        "Helm + Kustomize integration",
                        "Sync waves and hooks",
                        "Canary/Blue-green deployments with Flagger",
                        "Drift detection and self-healing",
                        "Secrets management with Sealed Secrets or External Secrets"
                    ],
                    "resources": [
                        "ArgoCD Documentation",
                        "Flux Documentation",
                        "\"GitOps and Kubernetes\" by Billy Yuen"
                    ]
                }
            },
            {
                "id": "p3-10",
                "title": "Apache Kafka",
                "desc": "Topics, partitions, consumers, producers, Kafka Connect, KSQL",
                "tags": [
                    "Deep"
                ],
                "guide": {
                    "goal": "Build real-time data pipelines and event-driven architectures with Kafka. Handle massive throughput with proper partitioning strategies.",
                    "build this": "Build a Real-time Analytics Pipeline: application events → Kafka → Kafka Connect → Elasticsearch for search + S3 for long-term storage. Add KSQL for real-time stream processing (counting events per minute).",
                    "key concepts": [
                        "Topics, partitions, replication factor",
                        "Producers: partitioning strategies, acks, retries",
                        "Consumers: consumer groups, rebalancing, offset management",
                        "Kafka Connect: source and sink connectors",
                        "KSQL / Kafka Streams: stream processing",
                        "Schema Registry: Avro, JSON, Protobuf",
                        "Monitoring: JMX metrics, lag monitoring"
                    ],
                    "resources": [
                        "Kafka Documentation",
                        "\"Kafka: The Definitive Guide\" by Gwen Shapira",
                        "Confluent Platform tutorials"
                    ]
                }
            },
            {
                "id": "p3-11",
                "title": "RabbitMQ / Redis Pub-Sub",
                "desc": "Message queues, dead letter queues, priority queues",
                "tags": [
                    "Cloud"
                ],
                "guide": {
                    "goal": "Use message queues for reliable asynchronous communication between services. Handle failures gracefully.",
                    "build this": "Build an Order Fulfillment System: order placed → RabbitMQ queue → inventory service processes → shipping service processes → notification service sends email. Add DLQ for failed orders and retry logic.",
                    "key concepts": [
                        "RabbitMQ: exchanges, queues, bindings, routing keys",
                        "Exchange types: direct, topic, fanout, headers",
                        "Dead Letter Exchanges (DLX) for failed messages",
                        "Message TTL and queue limits",
                        "Priority queues",
                        "Redis Pub/Sub: simple messaging, limitations",
                        "Redis Streams: persistent messaging"
                    ],
                    "resources": [
                        "RabbitMQ Documentation",
                        "Redis Pub/Sub Docs",
                        "\"RabbitMQ in Depth\" by Gavin Roy"
                    ]
                }
            },
            {
                "id": "p3-12",
                "title": "Microservices Patterns",
                "desc": "Service discovery, circuit breakers, API gateway, sagas, CQRS",
                "tags": [
                    "Deep"
                ],
                "guide": {
                    "goal": "Design and build microservices that are resilient, scalable, and maintainable. Understand when microservices are appropriate vs monoliths.",
                    "build this": "Build a Microservices E-Commerce Platform: API Gateway (Kong/AWS API Gateway) → User Service → Product Service → Order Service → Payment Service → Notification Service. Use gRPC for internal communication, implement saga pattern for distributed transactions.",
                    "key concepts": [
                        "API Gateway: routing, rate limiting, authentication",
                        "Service Discovery: Consul, Eureka, K8s DNS",
                        "Circuit Breaker: Hystrix/Resilience4j patterns",
                        "Saga Pattern: choreography vs orchestration",
                        "CQRS: separate read and write models",
                        "Event Sourcing: event store as source of truth",
                        "gRPC: protobuf, streaming, bi-directional",
                        "Sidecar pattern: Envoy, Istio proxy"
                    ],
                    "resources": [
                        "Microservices.io Patterns",
                        "\"Building Microservices\" by Sam Newman",
                        "\"The Tao of Microservices\" by Richard Rodger"
                    ]
                }
            },
            {
                "id": "p3-13",
                "title": "Distributed Systems Fundamentals",
                "desc": "CAP theorem, consensus, idempotency, distributed transactions",
                "tags": [
                    "Deep"
                ],
                "guide": {
                    "goal": "Understand the fundamental challenges of distributed systems and how to solve them. This is what separates senior engineers from juniors.",
                    "build this": "Design a Distributed Task Scheduler: multiple workers pick up jobs from a queue, ensure exactly-once processing, handle worker crashes, implement leader election for coordination. Use Redis or ZooKeeper for distributed locks.",
                    "key concepts": [
                        "CAP Theorem: practical implications",
                        "Consensus: Raft, Paxos (understand concepts)",
                        "Idempotency: designing for retries",
                        "Distributed transactions: 2PC, SAGA, outbox pattern",
                        "Consistency models: strong, eventual, causal",
                        "Vector clocks and conflict resolution",
                        "Distributed locking: Redis Redlock, ZooKeeper",
                        "Backpressure and load shedding"
                    ],
                    "resources": [
                        "\"Designing Data-Intensive Applications\" by Martin Kleppmann (Ch 8, 9)",
                        "\"Distributed Systems\" by Maarten van Steen",
                        "Raft Consensus Visualization"
                    ]
                }
            }
        ]
    },
    {
        "id": "core",
        "badge": "★",
        "title": "Unautomatable Core Skills",
        "subtitle": "Ongoing | The skills AI cannot replace",
        "items": [
            {
                "id": "core-1",
                "title": "Problem Solving & Debugging",
                "desc": "Root cause analysis in production. Reading logs, traces, metrics under pressure.",
                "tags": [
                    "Critical"
                ],
                "guide": {
                    "goal": "Become the engineer who can fix anything at 2 AM. Debug production issues without panicking.",
                    "build this": "Participate in a production incident (or simulate one): app is down, CPU at 100%, memory growing. Use logs, metrics, traces, and profiling to find root cause. Write a detailed incident report.",
                    "key concepts": [
                        "Structured debugging: hypothesis → test → validate",
                        "Log analysis: grep, awk, structured logging (JSON)",
                        "Distributed tracing: OpenTelemetry, Jaeger, Zipkin",
                        "Profiling: CPU, memory, flame graphs",
                        "Binary search debugging: isolate the problem",
                        "Reproducing bugs: minimal test cases",
                        "Post-mortems: blameless, actionable, shared"
                    ],
                    "resources": [
                        "\"The Art of Debugging\" by Norman Matloff",
                        "\"Systems Performance\" by Brendan Gregg",
                        "OpenTelemetry documentation"
                    ]
                }
            },
            {
                "id": "core-2",
                "title": "System Thinking & Architecture",
                "desc": "Trade-off analysis, scalability decisions, tech stack selection. The big picture.",
                "tags": [
                    "Critical"
                ],
                "guide": {
                    "goal": "Make architectural decisions that stand the test of time. Understand trade-offs and communicate them effectively.",
                    "build this": "Design a System from Scratch: design a URL shortener, a ride-sharing app, or a social media feed. Document your decisions: why this database, why this cache, why this queue. Present to a friend and defend your choices.",
                    "key concepts": [
                        "Non-functional requirements: scalability, reliability, latency, cost",
                        "Trade-off analysis: consistency vs availability, speed vs cost",
                        "Technology selection criteria",
                        "Capacity planning and load estimation",
                        "Failure mode analysis",
                        "Architecture patterns: layered, hexagonal, clean",
                        "Documentation: ADRs (Architecture Decision Records)"
                    ],
                    "resources": [
                        "\"Designing Data-Intensive Applications\" by Martin Kleppmann",
                        "\"Software Architecture: The Hard Parts\" by Ford & Richards",
                        "DesignGurus.io for system design practice"
                    ]
                }
            },
            {
                "id": "core-3",
                "title": "Communication & Technical Writing",
                "desc": "Architecture docs, RFCs, incident reports, mentoring. Force multipliers.",
                "tags": [
                    "Must"
                ],
                "guide": {
                    "goal": "Write clearly, present confidently, and mentor effectively. These skills compound your technical abilities.",
                    "build this": "Write a Complete RFC: propose a new architecture change for your project. Include problem statement, options considered, trade-offs, implementation plan, and rollback strategy. Get feedback and iterate.",
                    "key concepts": [
                        "RFCs: structure, audience, decision-making",
                        "Architecture diagrams: C4 model, sequence diagrams",
                        "API documentation: OpenAPI, READMEs",
                        "Runbooks: step-by-step operational guides",
                        "Code review comments: constructive, specific, kind",
                        "Presenting: storytelling, visuals, handling questions",
                        "Mentoring: coaching, not telling"
                    ],
                    "resources": [
                        "\"Technical Writing for Engineers\" by Google",
                        "\"The Pyramid Principle\" by Barbara Minto",
                        "C4 Model for Architecture"
                    ]
                }
            },
            {
                "id": "core-4",
                "title": "Adaptability & Continuous Learning",
                "desc": "New frameworks, new AI models, new paradigms. Learn to learn fast.",
                "tags": [
                    "Must"
                ],
                "guide": {
                    "goal": "Develop a system for staying current. Technology changes fast; your ability to adapt is your competitive advantage.",
                    "build this": "Learn a New Technology in 1 Week: pick something completely new (e.g., Rust, Go, a new AI framework). Build a small project. Document what you learned, what was hard, and how you overcame it.",
                    "key concepts": [
                        "Learning frameworks: Feynman technique, spaced repetition",
                        "Deliberate practice: focused, feedback-driven",
                        "Building to learn: projects over tutorials",
                        "Community engagement: conferences, meetups, Discord",
                        "Teaching as learning: blog posts, talks, mentoring",
                        "Information diet: newsletters, podcasts, papers"
                    ],
                    "resources": [
                        "\"Ultralearning\" by Scott Young",
                        "\"A Mind for Numbers\" by Barbara Oakley",
                        "Newsletters: TLDR, Pointer, AI Engineer"
                    ]
                }
            },
            {
                "id": "core-5",
                "title": "Business Context & Product Sense",
                "desc": "Understanding why something is built, not just how. AI has no business context.",
                "tags": [
                    "Must"
                ],
                "guide": {
                    "goal": "Understand the business impact of your technical decisions. Build what matters, not what's technically interesting.",
                    "build this": "Analyze a Failed Product: pick a product that failed (e.g., Google+, Quibi). Analyze technical decisions vs business needs. Write a case study on what engineering could have done differently.",
                    "key concepts": [
                        "Business models: SaaS, marketplace, platform",
                        "Key metrics: MAU, ARR, churn, LTV, CAC",
                        "Product lifecycle: MVP, growth, maturity",
                        "User research: personas, journeys, pain points",
                        "Prioritization frameworks: RICE, MoSCoW",
                        "Technical debt: when to pay it down",
                        "ROI of engineering investments"
                    ],
                    "resources": [
                        "\"The Lean Startup\" by Eric Ries",
                        "\"Inspired\" by Marty Cagan",
                        "\"The Phoenix Project\" by Gene Kim"
                    ]
                }
            },
            {
                "id": "core-6",
                "title": "Code Review & Quality Judgment",
                "desc": "Reviewing AI-generated code critically. Knowing what's safe to ship.",
                "tags": [
                    "Critical"
                ],
                "guide": {
                    "goal": "Develop the judgment to know good code from bad code. This is especially critical when reviewing AI-generated output.",
                    "build this": "Conduct a Code Review Marathon: review 50 PRs (open source or your own). Categorize issues: security, performance, maintainability, readability. Build a personal checklist.",
                    "key concepts": [
                        "Security review: injection, XSS, auth bypasses",
                        "Performance: N+1, unbounded queries, memory leaks",
                        "Maintainability: complexity, coupling, testability",
                        "Readability: naming, comments, structure",
                        "AI-generated code review: hallucinations, subtle bugs",
                        "Constructive feedback: specific, actionable, kind",
                        "Automated checks: linters, SAST, dependency scanning"
                    ],
                    "resources": [
                        "\"Code Complete\" by Steve McConnell",
                        "\"Clean Code\" by Robert C. Martin",
                        "SonarQube / CodeQL for automated analysis"
                    ]
                }
            },
            {
                "id": "core-7",
                "title": "Security & Compliance Thinking",
                "desc": "Threat modeling, data privacy, regulatory requirements. AI doesn't understand liability.",
                "tags": [
                    "Must"
                ],
                "guide": {
                    "goal": "Build security into your systems from day one. Understand compliance requirements and how to meet them.",
                    "build this": "Perform a Security Audit on Your App: threat model (STRIDE), dependency scan (Snyk/Dependabot), penetration test (OWASP ZAP), and write a security runbook. Get a friend to try to break your app.",
                    "key concepts": [
                        "Threat modeling: STRIDE, attack trees",
                        "OWASP Top 10: understanding each category",
                        "Authentication: OAuth2, SAML, MFA",
                        "Authorization: RBAC, ABAC, policy engines",
                        "Data privacy: GDPR, CCPA, encryption at rest/transit",
                        "Secrets management: HashiCorp Vault, AWS Secrets Manager",
                        "Compliance: SOC2, ISO 27001 basics"
                    ],
                    "resources": [
                        "OWASP Top 10",
                        "\"Threat Modeling\" by Adam Shostack",
                        "\"The Tangled Web\" by Michal Zalewski"
                    ]
                }
            }
        ]
    },
    {
        "id": "books",
        "badge": "📚",
        "title": "Recommended Reading",
        "subtitle": "Books that compound over a career",
        "items": [
            {
                "id": "book-1",
                "title": "Designing Data-Intensive Applications",
                "desc": "Martin Kleppmann. The bible for backend engineers. Read it twice.",
                "tags": [
                    "Essential"
                ],
                "guide": {
                    "goal": "Understand how to build systems that handle data reliably, at scale, and with good performance. This book changes how you think about systems.",
                    "build this": "Read one chapter per week. After each chapter, apply the concepts to a system you're building or have built. Write a blog post or notes summarizing the key insights.",
                    "key concepts": [
                        "Reliability, scalability, maintainability",
                        "Data models: relational, document, graph",
                        "Storage and retrieval: B-trees, LSM trees",
                        "Encoding: JSON, binary, schema evolution",
                        "Replication: leader-follower, multi-leader",
                        "Partitioning: key range, hash",
                        "Transactions: ACID, isolation levels",
                        "Consistency and consensus"
                    ],
                    "resources": [
                        "Amazon / O'Reilly (buy the physical copy, you'll reference it for years)",
                        "Author's talks on YouTube",
                        "Supplementary: papers referenced in each chapter"
                    ]
                }
            },
            {
                "id": "book-2",
                "title": "Effective Java (3rd Edition)",
                "desc": "Joshua Bloch. Java best practices. Read alongside your Spring Boot learning.",
                "tags": [
                    "Java"
                ],
                "guide": {
                    "goal": "Write Java code that is correct, efficient, and maintainable. This book is the definitive guide to Java idioms and best practices.",
                    "build this": "Read 5 items per week while building your Spring Boot project. Apply each item immediately. Keep the book open next to your IDE as a reference.",
                    "key concepts": [
                        "Creating and destroying objects",
                        "Methods common to all objects",
                        "Classes and interfaces",
                        "Generics",
                        "Enums and annotations",
                        "Lambdas and streams",
                        "Methods",
                        "General programming",
                        "Exceptions",
                        "Concurrency",
                        "Serialization"
                    ],
                    "resources": [
                        "Amazon / O'Reilly",
                        "Joshua Bloch's talks and interviews"
                    ]
                }
            },
            {
                "id": "book-3",
                "title": "Clean Architecture",
                "desc": "Robert C. Martin. Software structure, dependencies, boundaries. Timeless.",
                "tags": [
                    "Architecture"
                ],
                "guide": {
                    "goal": "Design software with clear boundaries and dependencies that point inward. Make your systems testable, independent of frameworks, and independent of UI.",
                    "build this": "Refactor an existing project using Clean Architecture principles. Separate domain logic from framework code. Ensure you can swap the database or UI without touching business rules.",
                    "key concepts": [
                        "The Dependency Rule",
                        "Entities, Use Cases, Interface Adapters, Frameworks",
                        "Boundaries: what to protect",
                        "Dependency Inversion Principle",
                        "Testability by design",
                        "Plugin architecture"
                    ],
                    "resources": [
                        "Amazon / Prentice Hall",
                        "Uncle Bob's blog and talks",
                        "Clean Coders video series"
                    ]
                }
            },
            {
                "id": "book-4",
                "title": "System Design Interview (Vol 1 & 2)",
                "desc": "Alex Xu. Practical system design for interviews and real work.",
                "tags": [
                    "Interview"
                ],
                "guide": {
                    "goal": "Learn to design scalable systems under time pressure. Useful for both interviews and real architectural decisions.",
                    "build this": "Practice one system design problem per week. Draw the architecture, estimate capacity, discuss trade-offs, and identify bottlenecks. Record yourself explaining it.",
                    "key concepts": [
                        "Scaling from 0 to millions of users",
                        "Database selection and scaling",
                        "Caching strategies",
                        "Load balancing and CDNs",
                        "Message queues and async processing",
                        "Microservices design",
                        "Real-world case studies"
                    ],
                    "resources": [
                        "Amazon (both volumes)",
                        "ByteByteGo YouTube channel (Alex Xu)",
                        "DesignGurus.io"
                    ]
                }
            }
        ]
    },
    {
        "id": "avoid",
        "badge": "⚠️",
        "title": "Things To Avoid",
        "subtitle": "Career traps in the AI era",
        "items": [
            {
                "id": "avoid-1",
                "title": "Frontend-Only Roles",
                "desc": "AI generates React components from Figma in seconds. Vibe coding is commoditizing UI work.",
                "tags": [
                    "Danger"
                ],
                "guide": {
                    "goal": "Avoid roles where your only value is converting designs to code. AI tools (v0, Bolt, Lovable) already do this faster and cheaper.",
                    "build this": "If you're currently frontend-only, immediately start learning backend. Use your React skills as a foundation, not a ceiling. Build full-stack projects that prove you can own the entire system.",
                    "key concepts": [
                        "AI tools generate UI from prompts and Figma",
                        "Component libraries are commoditized",
                        "Frontend-only engineers are most at risk from AI",
                        "Value is in system integration, not pixel-perfect CSS"
                    ],
                    "resources": [
                        "Build a full-stack project immediately",
                        "Learn one backend language deeply",
                        "Understand databases and APIs",
                        "Move toward full-stack or backend roles"
                    ]
                }
            },
            {
                "id": "avoid-2",
                "title": "Tutorial Dependency",
                "desc": "Watching tutorials without building. You learn by debugging broken code, not by following along.",
                "tags": [
                    "Trap"
                ],
                "guide": {
                    "goal": "Tutorials give you false confidence. You only learn when things break and you have to fix them yourself.",
                    "build this": "Stop watching tutorials for 30 days. Build projects using only documentation and AI tools. When stuck, read docs or ask AI, don't watch a video. Document what you learned from each struggle.",
                    "key concepts": [
                        "Tutorial trap: feeling productive without learning",
                        "Passive consumption vs active problem-solving",
                        "Copy-paste coding doesn't build understanding",
                        "Debugging is where real learning happens"
                    ],
                    "resources": [
                        "Documentation-first approach",
                        "Build projects from scratch",
                        "Use AI as a tutor, not a crutch",
                        "Contribute to open source"
                    ]
                }
            },
            {
                "id": "avoid-3",
                "title": "Pure CRUD Development",
                "desc": "AI generates CRUD APIs in seconds. The value is in the system around the CRUD, not the CRUD itself.",
                "tags": [
                    "Danger"
                ],
                "guide": {
                    "goal": "CRUD is a solved problem. AI generates it instantly. Your value is in what surrounds the CRUD: validation, business logic, integrations, performance, security.",
                    "build this": "Take a simple CRUD app and add real complexity: multi-tenancy, real-time updates, offline sync, complex permissions, audit logging, data import/export, analytics. That's where the engineering is.",
                    "key concepts": [
                        "AI generates CRUD from database schema",
                        "Business rules and validations are the differentiator",
                        "System integration requires human judgment",
                        "Performance optimization is never auto-generated"
                    ],
                    "resources": [
                        "Focus on business logic complexity",
                        "Learn system design and architecture",
                        "Build integrations with external systems",
                        "Optimize for performance and scale"
                    ]
                }
            },
            {
                "id": "avoid-4",
                "title": "\"AI Wrapper Only\" Development",
                "desc": "Simple OpenAI API calls are commoditized. The moat is in retrieval, agents, and system integration.",
                "tags": [
                    "Trap"
                ],
                "guide": {
                    "goal": "Calling OpenAI API and showing the result is not a product. It's a demo. Real value comes from the system around the LLM.",
                    "build this": "Build something that can't be replicated in a weekend: multi-source RAG, agent workflows with 5+ tools, human-in-the-loop approval, custom fine-tuning, domain-specific embeddings, production observability.",
                    "key concepts": [
                        "API calls are trivial; system design is hard",
                        "Retrieval quality is the moat",
                        "Agent workflows with real tools are defensible",
                        "Domain expertise can't be copied"
                    ],
                    "resources": [
                        "Build RAG with custom data and advanced patterns",
                        "Create agent systems with multiple tools",
                        "Develop domain-specific solutions",
                        "Focus on production reliability"
                    ]
                }
            },
            {
                "id": "avoid-5",
                "title": "Ignoring AI Tools",
                "desc": "The gap between engineers who use AI and those who don't widens daily. Don't be the latter.",
                "tags": [
                    "Danger"
                ],
                "guide": {
                    "goal": "You won't lose your job to AI. You'll lose it to a human who uses AI to work 10x faster than you. The gap is widening every day.",
                    "build this": "Start today. Use Cursor for your next coding session. Use Claude Code for your next refactor. Use AI for documentation, testing, and code review. Measure your productivity before and after.",
                    "key concepts": [
                        "AI-augmented engineers are 1.5-3x more productive",
                        "42% of production code is already AI-generated",
                        "The gap compounds over time",
                        "Not using AI is a competitive disadvantage"
                    ],
                    "resources": [
                        "Cursor, Claude Code, GitHub Copilot",
                        "AI for code review and documentation",
                        "AI for learning new technologies",
                        "AI for debugging and testing"
                    ]
                }
            }
        ]
    }
];
